### ISSUE TITLE
Torii graphql events and transactions api

### ISSUE THREAD

**Issue by broody** [dojoengine/book#103]
Quick note below about new APIs in graphql. 

Only events and transactions emitted from your world are indexed.
- `events` - We store the key values, data, and txn hash. These events are filterable by keys like entities query. Supports pagination.

- `transactions` - we're only storing transaction data for now, transaction receipt can be support in the future. No filtering. Supports pagination.

**Comment by gianalarcon** [comment]
We should add this like in the ..Torii/Graphql section right?

**Comment by broody** [comment]
> Do we should add this in the ..Torii/Graphql section right?

Yeah for sure!
