### ISSUE TITLE
First example of system not clear

### ISSUE THREAD

**Issue by glihm** [dojoengine/book#124]
The first example of a system is in the [architecture overview](https://book.dojoengine.org/cairo/overview.html#spawn-function---a-dojo-system) relative to the `spawn` function.

The text says:
```
In the spawn function, take note of the second parameter: the IWorldDispatcher interface.
This provides a gateway to the world contract.
By integrating it into the function, it enables the get! and set! macros to interface directly with the world contract.
```
However the function looks like:
```rust
fn spawn(self: @ContractState) {
    // Access the world dispatcher for reading.
    let world = self.world_dispatcher.read();

    // get player address
    let player = get_caller_address();

    // dojo command - get player position
    let position = get!(world, player, (Position));

    // dojo command - set player position
    set!(world, (Position { player, vec: Vec2 { x: 10, y: 10 } }));
}
```
Is this related to the fact that without using `[dojo::contract]` the user has to explicitly pass the world dispatcher? Should we update the code example, or modify this text?

**Comment by gianalarcon** [comment]
We don't have to pass the world dispatcher anymore. We have to update the text.
