### ISSUE TITLE
Add guide for using self-hosted world and slot deployment

### ISSUE THREAD

**Issue by JunichiSugiura** [dojoengine/book#142]

**Comment by ponderingdemocritus** [comment]
Do you mean running Katana outside of slot?

**Comment by ponderingdemocritus** [comment]
@JunichiSugiura do you still want to tackle this?

**Comment by JunichiSugiura** [comment]
I don't have a capacity rn rn. If anyone else can take this, I'm happy to provide necessary support.

I still need to implement the way to deploy metadata to ipfs without deploying to slot tho.
