### ISSUE TITLE
Add common errors section

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/book#169]
Ideally we wouldn't need this, but might make sense to have one for now. Plus this will help Sensei answer questions if people post the errors.

- Dojo.js
- Dojo core
- Unity

**Comment by cristianFleita** [comment]
Hello Loaf! I've been using the Unity SDK since the Dojo Jam. I'd like to contribute to the Unity SDK by adding more details to the sections such as examples for beginners and creating a common problems section.

**Comment by ponderingdemocritus** [comment]
Great! This is very much needed. Let me make a specific task and assign you.

**Comment by ponderingdemocritus** [comment]
Please comment on #180 so I can assign you
