### ISSUE TITLE
I18n Translate

### ISSUE THREAD

**Issue by Nadai2010** [dojoengine/book#174]
Hello team, @tarrencev  I would like to know if the translations will eventually be added automatically,  since I added version 0.2.0, they made changes and the Spanish version was not added, which must be done again. 

We have formed a team with @cryptonerdcn and other international translators, who translate starknet book, Cairo book, starknet by example... (we also correct errors in syntax or support new content) and we would like to be organized to start the year with the idea of having everything translated and updating every 15 days in each project. 

To do this, we would like to know your opinion and how you are going to handle the translations in dojobook and to know if our initiative would be part of your plans or rewards. 

Thanks greetings

**Comment by gianalarcon** [comment]
@ponderingdemocritus

**Comment by ponderingdemocritus** [comment]
Hi @Nadai2010 we have built an GPT translation system, however it's not perfect it could do with a review.

Since we want to support a lot of languages, ideally we come up with a pipeline and then have reviewers. This way GPT can do most of the work, and the language specalist can review it easily.

What do you think?

**Comment by Nadai2010** [comment]
Hello @ponderingdemocritus , I think that for some languages it can help a lot, for others like Chinese, I do not know what to think (What do you think @cryptonerdcn ?) 

In Spanish we can try and then make sense of the translation ourselves, I think it is a good idea. 

We have a dedicated group for translations in TG, I can send you the invitation by DM, my TG is @JavierCh7 

Thank you very much

**Comment by ponderingdemocritus** [comment]
I will create a channel in the discord for this - it's more organised

**Comment by Nadai2010** [comment]
Perfect, we can continue the conversation there

**Comment by ponderingdemocritus** [comment]
Could we just use google translate rather then maintaining all the languages?
