### ISSUE TITLE
Document new address parsing for arguments

### ISSUE THREAD

**Issue by glihm** [dojoengine/book#179]
This PR https://github.com/dojoengine/dojo/pull/1434 is introducing a new way to pass a socket address to a service.

`:u16` -> will be considered as a port, and `localhost` is automatically added.
`hostname` -> will only consider the hostname.
`hostname:port` -> fully qualified address.

**Comment by faytey** [comment]
Is this issue still up, i'd like to attempt it

**Comment by ponderingdemocritus** [comment]
have assigned!

**Comment by faytey** [comment]
Please i have a couple of questions @ponderingdemocritus firstly where exactly am I to make these changes, secondly is this the correct parsing reference to use  #[arg(long, value_name = "SOCKET", default_value = ":5050", value_parser = parse_socket_address)]
    rpc: SocketAddr,
