### ISSUE TITLE
[enhancement]: Unity documentation

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/book#180]
- Add examples
- Improve overall structure

**Comment by ponderingdemocritus** [comment]
assigned!

**Comment by cristianFleita** [comment]
I am suggesting the inclusion of the following sections. I would appreciate your feedback.

### 1. Overview:
*  A detailed introduction to the SDK with definitions of key concepts.
### 2. Prerequisites:
* Details on the minimum required version of Dojo.
* Instructions on setting up the package in Unity.
* Information about Dojo models.
### 3. Development:
* Covers Unity setup.
* Guidance on representing Dojo models within Unity.
* Explanation of data type bindings.
* Inclusion of examples showcasing system calls, providing practical insights into implementation.
### 4. Example with starter repo
### 5. Common Problems:
* Detail issues that users might face during SDK utilization.

Also, I would like to know if it's ok to submit individual pull requests for each proposed section

**Comment by ponderingdemocritus** [comment]
this sounds all great. Some points

- if you reuse dojoup setup instructions, please use or create the mdx components so we can keep the book DRY
- yes! submit these in stages so we can have updates asap

**Comment by tarrencev** [comment]
Closing in favor of #208
