### ISSUE TITLE
Update contributors.md

### ISSUE THREAD

**Issue by cristianFleita** [dojoengine/book#189]
The link to the [contributing guidelines](https://github.com/dojoengine/book/blob/main/src/misc/contributors.md) in the readme file is broken and it leads to outdated instructions related to the Rust book.

I would like to help by updating it with instructions for installing dependencies and running the book locally. Please let me know if this is currently unattended.

**Comment by gianalarcon** [comment]
Hi @cristianFleita , I fixed the broken link on this PR #191. Now you can check the instructions and improve it with your suggestions.
