### ISSUE TITLE
Add a paragraph to explain upgradibility concerns

### ISSUE THREAD

**Issue by glihm** [dojoengine/book#190]
Upgrading a system is fairly risk-free storage wise.
However, migrating new models can cause data loss.

We should add a section about this.
Here is a brief answer given on discord, should be reworded with some examples.

```
If the model has changed, but they keys fields are not impacted, you'll be able to keep retrieving the model data at the correct storage location.
However, modifying the fields of a model impacts how it is stored in the storage. So adding some fields to it should not be that problematic (or only removing some).
Hence, if you change some types of existing fields, you may end up with corrupted data. 
If you change the keys, then the storage location of your model's data is computed differently, and result to a different storage location. 
But changing a model fields (and not the keys), at the next write by a system, you'll overwrite the storage with new data layout. 
So even if dojo is not using the storage abstraction #[storage], it still rely on a layout on how data are packed and written into the storage (defined by the model fields order and type).
```

**Comment by ebukizy1** [comment]
will love to be assign this, can i have it

**Comment by glihm** [comment]
> will love to be assign this, can i have it

Hey! Thanks for considering contributing @ebukizy1! If you see where to put this information, let's go and propose a modification related to that.
Feel free to reach out if you have questions.

**Comment by rsodre** [comment]
Related to this, I think it is to explain in detail...

* how Model data is packed
* can we update a Model and not f#*k up the data?
* can a field type be changed?
* can new fields be added?
* can fields be reordered?
* can fields be renamed?

**Comment by glihm** [comment]
> Related to this, I think it is important to explain in detail...
> 
>     * how Model data is packed
> 
>     * can we update a Model and not f#*k up the data?
> 
>     * can a field type be changed?
> 
>     * can new fields be added?
> 
>     * can fields be reordered?
> 
>     * can fields be renamed?

That's a very good FAQ yes, with this people should get a good idea of how it works, and what they can/can't do. :+1: 
We are working to make the storage more flexible, at the moment of this code being merged, we should adjust the text.

**Comment by ebukizy1** [comment]
okay thanks for assigning me the task already on it just do final structuring
