### ISSUE TITLE
Improve Sozo Documentation

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/book#203]
- [ ] Examples using Sozo with L3s including setting up the .toml
- [ ] Sozo architecture and plans
- [ ] New manifest system with overlays
- [ ] Creating an Account on a Katana using sozo
- [ ] Adding new account clash hashes via sozo
- [ ] Workflow using `sozo dev`
- [ ] Contributing to sozo

**Comment by glihm** [comment]
Depends on https://github.com/dojoengine/dojo/issues/1574 for account stuff.
