### ISSUE TITLE
Update theory

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/book#207]
- [x] Overhaul and review theory and introduction sections. This should point to examples and build out the corpus of links around AW and provable games
- [x] Update Cairo Ecosystem documentation and build out more examples
- [ ] Expand FAQs out to all relevent recent questions asked in the discord and at conferences 
- [x] Add a Why provable games?

**Comment by Zeegaths** [comment]
Just the FAQs?

**Comment by Zeegaths** [comment]
Please provide more clarity on the issue. Should I work on all the 4 tasks or just the unchecked 3rd task?
