### ISSUE TITLE
Dojo.js Documentation

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/book#209]
- [ ] Core documentation including examples of usage in vanilla JS
- [ ] React documentation including examples of usage in React
- [ ] Torii-client explanation 
- [ ] running `npx create-dojo` 
- [ ] Explanation and code snippets of Recs state library
- [ ] E2E example using dojo.js
- [ ] Contributing to Dojo.js (point to repo)

**Comment by caillef** [comment]
I can start working on this one, can you assign me?

**Comment by glihm** [comment]
@ponderingdemocritus would you have more info on this? I guess it's in the book itself.

**Comment by caillef** [comment]
I started working on this, I will try to finish it by Saturday.

do you have more info about the `E2E example using dojo.js` @ponderingdemocritus?
Can I use the dojo-starter project or should I work on something different?
I am not sure I will have the time to fit this E2E example in the PR though if it's more than a step by step guide of how to make the React version of the dojo-starter.
