### ISSUE TITLE
Update Introduction - What is Dojo?

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/book#210]
- [x] What is Dojo? Concise.
- [ ] What is the goal?
- [ ] How does Dojo compare to other onchain game engines (a table)
- [x] What Dojo doesn't give you?
- [x] Why Dojo?
- [x] The Dojo Stack overview

**Comment by estheroche** [comment]
@ponderingdemocritus kindly assign to me

**Comment by LawrenceEzealor** [comment]
@ponderingdemocritus can i jump on this?

**Comment by od-hunter** [comment]
Hello @ponderingdemocritus , can I be assigned this please? Below are some of the documentations I've done:

https://github.com/keep-starknet-strange/joyboy/pull/143#event-13034455918

https://github.com/horuslabsio/Starknet-Scaffold/pull/94#event-13007360671

https://t.co/ZgK0ccPZpw

https://t.co/GnBqVQPECz

I’m available to work please.🙏🏾
