### ISSUE TITLE
Images needed

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/book#211]
**Theory**
- [ ] What is Dojo?

**Architecture**
- [ ] Overview - A high level look at all the parts of the Cairo Architecture and how they fit together. This should be simple enough and the following sections should go into more detail
- [ ] World - Image showing how the world is the center of it all. 
- [ ] Systems 1 - Show how a user interacts with a System. Users call systems directly and pass in a world address, they don't call the world address.
- [ ] Systems 2 - Defining Systems (update existing image that is already there)
- [ ] Models 1 - Show a ORM of a small example world and how entities share models where possible.
- [ ] Models 2 - How Models differ from traditional tables. Also show how they are compressed.
- [ ] Commands - Explain how commands are shorthand for calls.
- [ ] Authorisation - Update current image that already exists
- [ ] Entities - Explain Entities and the difference between dojo and pure ECS

**Comment by themujahidkhan** [comment]
Hi @ponderingdemocritus 

I want to work on this issue. Can you please share a reference so I can get the idea?

**Comment by ponderingdemocritus** [comment]
Hi @themujahidkhan thanks for offering. This task as already been assigned sorry. A lot of the other issues are open however!

**Comment by clicksave** [comment]
Thanks for highlighting these!

**Comment by Viral-Digital** [comment]
Hi @ponderingdemocritus

I want to work on this issue. Can you please share a reference so I can get the idea of what it entails?
