### ISSUE TITLE
outdated `sozo` register documentation

### ISSUE THREAD

**Issue by kwkr** [dojoengine/book#214]
Currently:

![image](https://uploads.linear.app/bbdecfa0-62ba-4d64-888d-44b699ecea41/f6146da5-1172-4c82-a423-9106f8e9bcf7/c5563853-d412-4648-8ccd-0495d872a96f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2JiZGVjZmEwLTYyYmEtNGQ2NC04ODhkLTQ0YjY5OWVjZWE0MS9mNjE0NmRhNS0xMTcyLTRjODItYTQyMy05MTA2ZjhlOWJjZjcvYzU1NjM4NTMtZDQxMi00NjQ4LThjY2QtMDQ5NWQ4NzJhOTZmIiwiaWF0IjoxNzA5NjgyNjE1LCJleHAiOjMzMjgwMjQyNjE1fQ.1_usQBPFfO3xkSaGYsPEnkiWsL-olRkx2nTHt7-Cd6k)

When run from source:

![image](https://uploads.linear.app/bbdecfa0-62ba-4d64-888d-44b699ecea41/d1217660-3fcb-49ff-90b8-8fa9182c5eee/870a61e0-48e1-4124-a911-ab4f1246585e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2JiZGVjZmEwLTYyYmEtNGQ2NC04ODhkLTQ0YjY5OWVjZWE0MS9kMTIxNzY2MC0zZmNiLTQ5ZmYtOTBiOC04ZmE5MTgyYzVlZWUvODcwYTYxZTAtNDhlMS00MTI0LWE5MTEtYWI0ZjEyNDY1ODVlIiwiaWF0IjoxNzA5NjgyNjE1LCJleHAiOjMzMjgwMjQyNjE1fQ.nchvLenXKYb0bTjiaHpwj0ra_KxuBRbit8BBHO32B8g)

**Comment by glihm** [comment]
Completed in #215.
