### ISSUE TITLE
Custom Event entry is missing mandatory enum Event

### ISSUE THREAD

**Issue by rsodre** [dojoengine/book#232]
[Custom Events](https://book.dojoengine.org/cairo/events#custom-events) need to declare `enum Event` that is not mentioned in the Book.

See declaration on `dojo-starter`:
https://github.com/dojoengine/dojo-starter/blob/main/src/systems/actions.cairo#L16-L28

Please address...

* Why is that enum required?
* Where should we place this enum? I can only build when it is inside the system that uses it, can I declare outside?
* Eternum has [one enum in each system](https://github.com/search?q=repo%3ABibliothecaDAO%2Feternum+enum+Event+language%3ACairo&type=code&l=Cairo)

**Comment by ebukizy1** [comment]
i will love to work on this. assign this to me

**Comment by ponderingdemocritus** [comment]
have assigned you @ebukizy1
