### ISSUE TITLE
Installed Scarb version must match Cairo version

### ISSUE THREAD

**Issue by rsodre** [dojoengine/book#235]
For the language server to work properly, the system Scarb version must match the project's Cairo version.

I don't know if that should be on [Setup 2. Install Scarb Package Manager](https://book.dojoengine.org/getting-started/setup#2-install-scarb-package-manager) or [Config](https://book.dojoengine.org/cairo/config#config)

The syntax for installing a specific Scarb version according to [swmansion](https://docs.swmansion.com/scarb/download.html#install-via-installation-script) is:

`curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh  -s -- -v 2.4.0`

**Comment by ponderingdemocritus** [comment]
Let's inlcude this in the https://book.dojoengine.org/getting-started/quick-start
