### ISSUE TITLE
Detailed explanation around the new RTC methods and Events

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/book#236]
It is now possible to stream events via torii over RTC opening up usecases.

These events are offchain - but recorded into torii like a regular model change, so they are gasless messaging essentially.

https://github.com/dojoengine/dojo/blob/main/examples/spawn-and-move/src/actions.cairo#L30

Such as:

- NFT Orderbooks
- RTC Chat
- Gasless games

Write up detailed documentation around this new feature.

**Comment by jerrywise4u2c** [comment]
will love to work on this... assign this to me

**Comment by ebukizy1** [comment]
I am eager to dive into this opportunity. I believe my extensive studies and experience make me well-prepared to take on this challenge.

**Comment by ebukizy1** [comment]
@ponderingdemocritus  it  seems this issue has not been assign to anyone can i jump on it
