### ISSUE TITLE
Dojo Cairo Style Guide

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/book#257]
We should build a 'Best Practices and Idiomatic Dojo'. This will help standardise how projects are designed and subsequently understood when they are studied.

- [ ] Align participants and gather feedback
- [ ] Build guide within book

Some potential areas:

- [ ] Arranging imports
- [ ] Designing Systems
- [ ] Designing Models
- [ ] Designing Traits
- [ ] Working with Large projects
- [ ] lib.cairo structure
- [ ] Testing structure
- [ ] Monorepos

**Comment by ebukizy1** [comment]
Good day Please assign this task to me so I can start working on it immediately.

**Comment by ScottyDavies** [comment]
I am open to work on this @ponderingdemocritus
