### ISSUE TITLE
Broken links in book

### ISSUE THREAD

**Issue by princeibs** [dojoengine/book#258]
<img width="540" alt="image" src="https://github.com/dojoengine/book/assets/64266194/f0df231f-a01c-4cc9-a6a4-d4f86ec20279">

Most of the **Edit on Github** links leads to a 404 page on Github

<img width="1098" alt="image" src="https://github.com/dojoengine/book/assets/64266194/6d32d0e2-0c3e-4533-b97a-f188a8f8a1f7">

I can easily create a PR that fixes all the broken links

**Comment by ponderingdemocritus** [comment]
Hi could you please! Something must have change in a vocs version.
