### ISSUE TITLE
`slot` CLI Documentation

### ISSUE THREAD

**Issue by juandiegocv27** [dojoengine/book#261]
The current CLI documentation for 'Slot' lacks the comprehensive detail found in the 'Sozo/Katana' guides. We aim to bring 'Slot' up to par by clearly documenting all commands, arguments, options, and providing concise examples. #202

**Comment by juandiegocv27** [comment]
@milancermak @ptisserand @broody @thiscaspar I just created the issue, assign it to me

**Comment by kariy** [comment]
assigned :)

**Comment by juandiegocv27** [comment]
> assigned ![:)](https://static-cdn.jtvnw.net/emoticons/v2/1/default/light/1.0)

thank u, I tried to contacto you form discord but I dont finde the username :( (My discord user is JuglitoTT, and in telegram juandiegocar), and about the documentation, could you send me more about the issue and the part in the code the cofigure, I just see there's maybe a spot in  the the code of docs about Katana, maybe I need to configure the Katana.md?  @kariy

**Comment by kariy** [comment]
> thank u, I tried to contact to you from discord but I dont fin the the username :( (My discord user is juglitott, and in telegram juandiegocar), 

hmm, i cant find you username either. if you're in the Dojo discord server, you can find my name (same pfp) under the 'sensei' role.

> and about the documentation, could you send me more about the issue and the part in the code to cofigure,

For starters, you can take a look at all commands that `slot` has. You can learn about them by playing around with the `slot` CLI tool, and can learn more from reading the [source code](https://github.com/cartridge-gg/slot/tree/main/src) itself. We need to document the commands, arguments, option flags, etc.

You can just follow the pages [structure](https://github.com/dojoengine/book/tree/main/docs/pages/toolchain/sozo) for `sozo`, where each command and shared option is placed in their own `.md`/`.mdx` file.

> I just saw there's maybe a spot in the the code of docs about Katana, maybe I need to configure the Katana.md? @kariy

You don't have to do change anything under the Katana section, only Slot.
