### ISSUE TITLE
Add documentation for asdf-dojo

### ISSUE THREAD

**Issue by Jonatan-Chaverri** [dojoengine/book#263]
Add documentation on how to install and manage dojo versions using asdf-dojo.

**Comment by Jonatan-Chaverri** [comment]
@glihm let me know if I can take care of this one

**Comment by kariy** [comment]
yes i think we can have a small section about installing thru asdf in the quick start section.

**Comment by Jonatan-Chaverri** [comment]
@tarrencev @kariy created a PR to add dojo as part of asdf registry https://github.com/asdf-vm/asdf-plugins/pull/1003
