### ISSUE TITLE
Docs for `sozo account`

### ISSUE THREAD

**Issue by kariy** [dojoengine/book#272]
We added the `sozo account` command in [https://github.com/dojoengine/dojo/pull/1601](https://github.com/dojoengine/dojo/pull/1601) but the book isn't updated to include the documentation for it.

Add the documentation for it similar to other commands that we have for `sozo`.

Ref: [https://github.com/dojoengine/dojo/blob/main/bin/sozo/src/commands/account.rs](https://github.com/dojoengine/dojo/blob/main/bin/sozo/src/commands/account.rs)

```
λ sozo account
Manage accounts

Usage: sozo account [OPTIONS] <COMMAND>

Commands:
  new     Create a new account configuration without actually deploying.
  deploy  Deploy account contract with a DeployAccount transaction.
  fetch   Fetch account config from an already deployed account contract.
  help    Print this message or the help of the given subcommand(s)

Options:
  -v, --verbose...  Increase logging verbosity
  -q, --quiet...    Decrease logging verbosity
  -h, --help        Print help (see more with '--help')
  -V, --version     Print version
```

**Comment by jancris100** [comment]
Can you assign this to me please?

**Comment by lambda-0x** [comment]
@jancris100 done! feel free to reach out to me on discord if you have any questions.

**Comment by jancris100** [comment]
Done!

**Comment by jancris100** [comment]
Hi @kariy can you close this task please ? The task is done !
