### ISSUE TITLE
Document a 'Torii Integration' Example Using Unity

### ISSUE THREAD

**Issue by jimenezz22** [dojoengine/book#276]
Propose developing an example in Unity using Torii, including research on both tools, as well as documenting this example with clear and concise steps. 
- Dojo Unity SDK Setup: Learn how to integrate the Dojo.unity SDK into your Unity scene for seamless development.
- Calling Dojo Systems: Discover how to interact with various systems within your Dojo world directly from Unity.
- Building for Desktop & WebGL: Master the steps for building your onchain game for both desktop and WebGL platforms (using the Slot framework).
This issue is related with issue #204

**Comment by jimenezz22** [comment]
Hi @milancermak @ptisserand @broody @thiscaspar, I just created this issue, please assign it to me and meanwhile I'll start working on it

**Comment by cristianFleita** [comment]
Hey! Don’t forget to check out the Unity documentation in the book: https://book.dojoengine.org/client/sdk/unity. If you need any help, feel free to contact me!

**Comment by cristianFleita** [comment]
> Hi @milancermak @ptisserand @broody @thiscaspar, I just created this issue, please assign it to me and meanwhile I'll start working on it

Hey! Don’t forget to check out the Unity documentation in the book: https://book.dojoengine.org/client/sdk/unity. If you need any help, feel free to contact me!

**Comment by jimenezz22** [comment]
@cristianFleita Thanks for the reminder! I'll definitely check out the Unity documentation in the book DojoEngine Unity SDK Documentation. If I have any questions or need further assistance, I'll be sure to reach out. Appreciate the support!
