### ISSUE TITLE
katana: specifying class using name instead of class hash

### ISSUE THREAD

**Issue by kariy** [dojoengine/book#278]
Since https://github.com/dojoengine/dojo/pull/1975, we can now specify the class hash for a contract using a user-defined name. 

Prior to this change, in order for you to specify a specific class when defining a contract allocation, you have to explicitly provide a class hash to the class entry, which would later be the actual class hash of the class itself. 

With the new update, instead of a class hash that would affect the resultant state, you can just give the class a name (the scope of the name is only within the JSON file, so it doesn't affect the actual genesis state) when you want to specify which class a contract should have.

To give more context:

**Before** 

The class hash of the class will exactly be `0x10`.

```jsonc
{
   "contracts": {
      "0x1": {
         "class": "0x10",
         ...
      }
   },
   "classes": [
      {
         "class:" "...",
         "classHash": "0x10"
      }
   ]
}
```

**After** 

The class hash of the class will be computed directly from the class artifact, and the contract would still have the correct class.

```jsonc
{
   "contracts": {
      "0x1": {
         "class": "MyClass",
      }
   },
   "classes": [
      {
         "class:" "...",
         "name": "MyClass"
      }
   ]
}
```

**Comment by mimiethetechsis** [comment]
Hello @kariy, I can do this. Can it be given to me to work on?

**Comment by kariy** [comment]
> Hello @kariy, I can do this. Can it be given to me to work on?

assigned, thanks!
