### ISSUE TITLE
Add Concepts

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/book#282]
Dojo is quite a complicated piece of software with some big ideas. A page dedicated to outlining some of these high level concepts will help new people to understand.

- [ ] Dojo as a provable game engine
- [ ] Dojos model state system
- [ ] Dojo is not an ECS or an ORM - it's an onchain combination
- [ ] Dojo Contracts system 
- [ ] Autonomous Worlds as protocols
- [ ] Execution sharding with the dojo stack
- [ ] Automatic indexing of the state via torii

**Comment by coxmars** [comment]
Hi @ponderingdemocritus is this issue still available? I would like to help with these concepts 🫡

**Comment by ScottyDavies** [comment]
Hello @ponderingdemocritus I am open to work on this
