### ISSUE TITLE
Documentation on auto-auth from overlays

### ISSUE THREAD

**Issue by glihm** [dojoengine/book#294]

**Comment by Ejembiii** [comment]
@glihm I'd love to work on this if it's still open for contribution.

**Comment by Godtide** [comment]
@glihm Please assign this to me, I can work on it asap, but I'll require more details

**Comment by ScottyDavies** [comment]
Hi @glihm I am open to work on this

**Comment by od-hunter** [comment]
Hello @glihm , can I work on this please?

**Comment by glihm** [comment]
No more needed since `1.0.0`, using the `dojo_<profile>.toml` explain in the config section.
