### ISSUE TITLE
[testing] add details on cairo test runner cheatcodes

### ISSUE THREAD

**Issue by glihm** [dojoengine/book#300]
Currently Dojo is using Cairo test runner, where [few cheat codes](https://github.com/starkware-libs/cairo/blob/25733b7a57b5f43b08b7d61f947b0396b3743801/corelib/src/starknet/testing.cairo#L34) are available, but not much documented.

We should add in the testing chapter a section/page to explain each of them with examples.

**Comment by od-hunter** [comment]
Can I be assigned this project please?

**Comment by vicjuma** [comment]
I can handle this. Can it be assigned to me kindly

**Comment by glihm** [comment]
> Can I be assigned this project please?

As you commented first will assign to you if you feel confident about the work to be done here. Any idea to where you'll start?

**Comment by od-hunter** [comment]
Hi @glihm , I will go through the testing.cairo file to study and test the test functions. I will then create a new section explaining how each of them work with code examples.

**Comment by od-hunter** [comment]
Hello @glihm , I’m ready to be assigned by you so I can start work.

**Comment by od-hunter** [comment]
Thank you🙏🏾

**Comment by od-hunter** [comment]
Hello @glihm kindly review please

**Comment by od-hunter** [comment]
@glihm kindly review please
