### ISSUE TITLE
Dojo starter guide

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/book#322]
Overhaul the dojo starter guide to include the new SDK.

Remove the concept of ECS and more explain the framework and how it simplifies development.

**Comment by Iwueseiter** [comment]
Hi @ponderingdemocritus can I work on this?

**Comment by ScottyDavies** [comment]
Hello @ponderingdemocritus can i please be assigned this task?

**Comment by knownasred** [comment]
Hi @ponderingdemocritus. As talked on discord, I would be available to work on the documentation of the Dojo Godot SDK.

The actual SDK is not ready yet, but we are working on it, and writing documentation at the same time (and with the same persons) as the actual SDK code would be worth
