### ISSUE TITLE
drag and drop ui

### ISSUE THREAD

**Issue by hakikicode** [dojoengine/book#328]
to fully build GAMEFI on stark with pure ui dev features, connect wallet , deploy and even create tokenomics for the game. in game asset can be sold as well as template

**Comment by ShantelPeters** [comment]
Hi @hakikicode can i please be assigned to this issue

**Comment by hakikicode** [comment]
sure

**Comment by ShantelPeters** [comment]
> sure

@hakikicode should I go ahead ,Am I assigned ?

**Comment by hakikicode** [comment]
Yea go ahead

**Comment by ShantelPeters** [comment]
Hi sir please can you enlighten me more on this issue so I know how to go
about it please..
