### ISSUE TITLE
0.3.0 Overhaul

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/book#60]
- [x] Getting Started
- [x] Architecture 
- [x] Testing
- [x] Dojo Modules
- [x] Onchain chess
- [x] SDKs
- [x] Deployment
- [x] Dojo starters

**Comment by kariy** [comment]
maybe its better to create individual issue for the `0.3.0` update?

**Comment by ponderingdemocritus** [comment]
yep I will! This was for my sanity first

**Comment by Akinbola247** [comment]
I'd like to work on updating the onchain-chess to 0.3.0

**Comment by kariy** [comment]
> I'd like to work on updating the onchain-chess to 0.3.0

hey, @Akinbola247 feel free to open a separate issue for this, and i'll assign it to you.

**Comment by Akinbola247** [comment]
Alright! great!

**Comment by Akinbola247** [comment]
hi @kariy i already created the issue here #71
