### ISSUE TITLE
Add details on Starkli

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/book#67]
We should include a section on how to interact with a dojo stack with Starkli

This should include:
- Working with Katana
- Working with remote Starknet

**Comment by gianalarcon** [comment]
Hi, I'm interested about working on this one. I have few questions
- **Working with Katana** Here you mean we can show how to deploy using katana and starkli? So it means instead of `sozo build ` we can use `starkli declare/deploy`? If I am wrong can you give more details what we can include from starkli here. 
- **Working with remote Starknet** It means work with RPC provider(alchemy/infura) or Madara? 

Thank you

**Comment by ponderingdemocritus** [comment]
Firstly we should just explain how you can use Starkli with katana as a testnet, then expand from there.

There is probably some crossover between sozo and starkli which we should explore

**Comment by Akinbola247** [comment]
@ponderingdemocritus So I’ve been exploring starkli with @gianalarcon, starkli works alongside scarb. On regular Starknet contracts, scarb complies into a single sierra_program json file but sozo compiles into multiple sierra json in the target folder. And when declaring with starkli, it requires a single sierra_program file  But sozo compiles into multiple sierra_program, it now begs the question which of the sierra_program will we declare?…I tried declaring the world sierra_program, it returned the hash unfortunately when I tried to deploy to katana locally with starkli, it failed…..is there any suggestion?

**Comment by gianalarcon** [comment]
> Firstly we should just explain how you can use Starkli with katana as a testnet, then expand from there.
> 
> There is probably some crossover between sozo and starkli which we should explore

Is it possible to work with katana as a testnet? I thought it is only for local development/devtnet

**Comment by Cevedale** [comment]
Hey, maybe i can help you 

Working with Katana
Installation:

Ensure you have Python and Pip installed on your system.
Install Katana using the following command:
bash
Copy code
pip install katana-eth
Initialize a Project:

Create a new directory for your project and navigate into it.
Run the following command to initialize a Katana project:
bash
Copy code
katana init
Smart Contract Development:

Write your StarkNet smart contract using Katana's development environment.
Use the following command to compile your contract:
bash
Copy code
katana compile <contract_file>
Deployment:

Deploy your smart contract to the StarkNet testnet or mainnet using:
bash
Copy code
katana deploy
Interact with Smart Contract:

Once deployed, interact with your smart contract using Python or any compatible language.
Working with Remote Starknet
Install Starknet SDK:

Install the Starknet SDK on your local machine:
bash
Copy code
pip install starknet
Set Up Starknet Project:

Create a new directory for your Starknet project and navigate into it.
Run the following command to initialize a Starknet project:
bash
Copy code
starknet init
Write and Compile Smart Contract:

Write your StarkNet smart contract in the contracts directory.
Compile the smart contract using:
bash
Copy code
starknet-compile <contract_file>
Deploy Smart Contract:

Deploy the smart contract to the StarkNet testnet or mainnet:
bash
Copy code
starknet deploy --contract <contract_address>
Interact with Remote Starknet:

Use the Starknet SDK to interact with the deployed smart contract remotely. For example:
python
Copy code
from starknet import Starknet

starknet = Starknet()

contract = starknet.contract(address="<contract_address>")

# Interact with your contract methods
result = contract.<method>().call()
Remember to replace placeholders like <contract_file>, <contract_address>, and <method> with your actual values.**

**Comment by ponderingdemocritus** [comment]
Lets include this within the book @Cevedale

**Comment by JameWade** [comment]
I used local katana when deploying the example contract in cairo book. Can I update my notes to katana book?

**Comment by JameWade** [comment]
> Lets include this within the book @Cevedale

I used local katana when deploying the example contract in cairo book. Can I update my notes to katana book?

**Comment by okhaimie-dev** [comment]
@ponderingdemocritus is this still relevant, I can try to attempt this issue by replacing katana with starkli as I practicing the examples in the docs.

**Comment by ponderingdemocritus** [comment]
yes! I have assigned you now. Create a new section Starkli section.

**Comment by ponderingdemocritus** [comment]
sorry @okhaimie-dev actually this has been worked on #175

**Comment by glihm** [comment]
#216 was merged and complete this.
