### ISSUE TITLE
Update Onchain Chess to 0.3.0

### ISSUE THREAD

**Issue by Akinbola247** [dojoengine/book#71]

**Comment by ponderingdemocritus** [comment]
assigned @Akinbola247

**Comment by gianalarcon** [comment]
@Akinbola247 let me now if you need some help here. We can work together on this one

**Comment by Akinbola247** [comment]
Just about time @gianalarcon . as per 0.3.0 convention, how do we handle a function argument of this nature `curr_position: (u32, u32)`, that needs to be passed into a system contract function. For example, if a piece needs to move from point (1,0) to point (2,2). these points are tuples, how can they be passed in as a single parameter? do i have to go through this route 
"let call_data = array![1.into(), 0.into(), 2.into(), 2.into(), white.into(), game_id];
 move_system.move(call_data);"  

or
I just make the call directly like this "move_system.move((1,0), (2,0), white.into(), game_id)";

**Comment by gianalarcon** [comment]
@Akinbola247  You can add me to your v0.3.0 onchain chess game to look into the whole code.

**Comment by gianalarcon** [comment]
We have migrated chess-dojo to v0.3.0. You can have a look here
https://github.com/Akinbola247/chess-dojo/tree/dev/gian
`sozo build` and `sozo test` works well.

We are gonna update and release the documentation soon!

**Comment by ponderingdemocritus** [comment]
amazing work! I will get the 0.3.0 live today, and then let us ship the updated tutorial next.

**Comment by Akinbola247** [comment]
@ponderingdemocritus the tutorial has been released, the PR has been created here #82 . kindly take a look at it while we await your feedback. the code reference for the tutorialv3 can be seen here https://github.com/Akinbola247/chess-dojo/tree/tutorialv3. `sozo build` and `sozo test` works as expected.

**Comment by rkdud007** [comment]
guys, i just noticed, we also need to update the index. currently dojo book doesn't show the tutorial chapter
