### ISSUE TITLE
Migrate ES to 0.3.0

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/book#75]
Migrate translation from 0.2.0 to 0.3.0

**Comment by Nadai2010** [comment]
Hello team, a pleasure to work on this. Are you ready to translate?

**Comment by Nadai2010** [comment]
Hello team @gianalarcon @ponderingdemocritus, here we have the new version, now everything is better structured, I have had to do everything from scratch since the messaget.pot flow is not the same, although this way I have been able to review everything better.

Whatever you need, I'm here
