### ISSUE TITLE
document impact of the video game on privacy

### ISSUE THREAD

**Issue by gogo2464** [dojoengine/book#8]
I fear about privacy when I debug dojo to write documentation.

The issue is that I fear to store infos on the blockchain. If as example, I left my name... it will stay forever on the blockchain.

Could someone provide great lines about privacy on dojo please?

It is mostly for me. I will include these in the doc as well.

**Comment by milancermak** [comment]
There's nothing special about Dojo in this regard. Whatever get stored on the blockchain is public as you mention.
